### ISSUE TITLE
Windows Python 3.5 AttributeError

### ISSUE THREAD

**Issue by zet4** [mitsuhiko/python-regex-scanner#1]
```
C:\Users\Alex\AppData\Local\Programs\Python\Python35\python.exe C:/Users/Alex/Documents/Projects/playground/__init__.py
Traceback (most recent call last):
  File "C:/Users/Alex/Documents/Projects/playground/__init__.py", line 124, in <module>
    ('underline', '_'),
  File "C:/Users/Alex/Documents/Projects/playground/__init__.py", line 77, in __init__
    pattern.groups = len(rules) + 1
AttributeError: can't set attribute
```

**Comment by ghost** [comment]
This script is for python 2. To use it in python 3, convert it through 2to3.
